---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: receivetest
  name: receivetest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receivetest
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: receivetest
    spec:
      containers:
      - image: geerd/receive-udp
        imagePullPolicy: IfNotPresent
        name: receivetest
        ports:
        - name: udpport
          protocol: UDP
          containerPort: 5000
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        env:
          - name: PORT
            value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: receivetest
  name: receivetest
spec:
  ports:
  - name: udptest
    port: 5000
    protocol: UDP
    targetPort: 5000
  selector:
    app: receivetest
  sessionAffinity: None
  type: ClusterIP