---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sendtcp
  name: sendtcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sendtcp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sendtcp
    spec:
      containers:
      - command:
        - sh
        - -c
        - while echo $counter; do counter=$((counter+1)); echo -n "$counter" | curl -m 2 10.38.253.2:319;sleep 5; done
        image: geerd/netcat:v2
        imagePullPolicy: IfNotPresent
        name: sendtcp
