---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: connectiontest
  name: connectiontest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connectiontest
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: connectiontest
    spec:
      containers:
      - command:
        - sh
        - -c
        - while echo $counter; do counter=$((counter+1)); echo -n "$counter" | curl -m 2 10.38.253.2 319; done
        image: geerd/netcat:v2
        imagePullPolicy: IfNotPresent
        name: connectiontest
